docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:3fa66.kube_apiserver.v1_18_1
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:3d9c7.kube_controller_manager.v1_18_1
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:96880.kube_scheduler.v1_18_1
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:cd2cc.kube_proxy.v1_18_1
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:dc140.pause.3_2
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:16dfb.etcd.3_4_3-0
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:ade4d.coredns.1_6_7
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:1c193.cni.v3_12_0
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:c687a.node.v3_12_0
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:6bee2.kube_controllers.v3_12_0
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:5e307.pod2daemon_flexvol.v3_12_0
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:fdcd9.multus.v3_4
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:38c6b.k8s_cni_sriov.stx_3_0-v2_2
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:cc24e.k8s_plugins_sriov_network_device.stx_4_0-v3_2-16-g4e0302ae
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:67d62.tiller.v2_16_1
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:7ca1b.armada.8a1638098f88d92bf799ef4934abe569789b885e-ubuntu_bionic
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:d3eb5.n3000_opae.stx_4_0-v1_0_0
docker pull registry.cn-hangzhou.aliyuncs.com/babyplus/get:efae9.kubernetes_entrypoint.v0_3_1
