docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:3fa66.kube_apiserver.v1_18_1 k8s.gcr.io/kube-apiserver:v1.18.1
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:3d9c7.kube_controller_manager.v1_18_1 k8s.gcr.io/kube-controller-manager:v1.18.1
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:96880.kube_scheduler.v1_18_1 k8s.gcr.io/kube-scheduler:v1.18.1
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:cd2cc.kube_proxy.v1_18_1 k8s.gcr.io/kube-proxy:v1.18.1
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:dc140.pause.3_2 k8s.gcr.io/pause:3.2
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:16dfb.etcd.3_4_3-0 k8s.gcr.io/etcd:3.4.3-0
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:ade4d.coredns.1_6_7 k8s.gcr.io/coredns:1.6.7
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:1c193.cni.v3_12_0 quay.io/calico/cni:v3.12.0
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:c687a.node.v3_12_0 quay.io/calico/node:v3.12.0
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:6bee2.kube_controllers.v3_12_0 quay.io/calico/kube-controllers:v3.12.0
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:5e307.pod2daemon_flexvol.v3_12_0 quay.io/calico/pod2daemon-flexvol:v3.12.0
docker tag registry.cn-hangzhou.aliyuncs.com/babyplus/get:fdcd9.multus.v3_4 docker.io/nfvpe/multus:v3.4
